# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
