# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_link_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='idTags',
            field=models.ManyToManyField(to='page.Tag'),
        ),
    ]
