# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20161118_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Link', models.CharField(max_length=2000)),
                ('FontAwesome Brand Tag', models.CharField(max_length=30)),
                ('FontAwesome Background Color', models.CharField(max_length=30)),
                ('FontAwesome Size', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='link',
            old_name='title',
            new_name='Title',
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
