# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20161211_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
    ]
