# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20161211_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='FontAwesome Brand Tag',
            new_name='FontAwesome Icon',
        ),
        migrations.AddField(
            model_name='social',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
