# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20161211_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
