# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20161211_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='FontAwesome Background Color',
        ),
        migrations.RemoveField(
            model_name='social',
            name='FontAwesome Icon',
        ),
        migrations.RemoveField(
            model_name='social',
            name='FontAwesome Size',
        ),
        migrations.RemoveField(
            model_name='social',
            name='Link',
        ),
        migrations.RemoveField(
            model_name='social',
            name='Nombre',
        ),
        migrations.AddField(
            model_name='social',
            name='fA_bkColor',
            field=models.CharField(default='', max_length=30, verbose_name='FontAwesome Background Color'),
        ),
        migrations.AddField(
            model_name='social',
            name='fA_brand',
            field=models.CharField(default='', max_length=30, verbose_name='FontAwesome Icon'),
        ),
        migrations.AddField(
            model_name='social',
            name='fA_size',
            field=models.CharField(default='fa-2x', max_length=30, verbose_name='FontAwesome Size'),
        ),
        migrations.AddField(
            model_name='social',
            name='link',
            field=models.CharField(default='', max_length=2000, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='social',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Nombre'),
        ),
    ]
